"""followers

Revision ID: 3025682bdef3
Revises: 4c4d7dd01a26
Create Date: 2020-11-05 14:23:57.646964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3025682bdef3'
down_revision = '4c4d7dd01a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
